name: CI/CD Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test || echo "No tests found, skipping..."

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 172.201.112.101
        username: Salahuddin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd devops-azure-lab
          git pull origin main
          docker-compose down
          docker-compose up -d --build

