script: |
  cd devops-azure-lab
  git pull origin main
  sudo docker compose down
  sudo docker compose up -d --build
  echo "⌛ Testing the API after deployment..."
  curl -f http://localhost:3000/test-db

